language: python
python:
  - '3.7'
cache:
  pip: true
  directories:
    - /home/travis/.yarn-cache/

before_install:
  - nvm install 14
  - source ./.ci_funcs.sh
install:
  - ci_install
script:
  - ci_script
