package:
  name: "theme-material-darcula"
  version: "1.0.5"

source:
  path: .
  git_rev: v1.0.5
  git_url: https://github.com/adhadse/theme-material-darcula

build:
    script: python setup.py install -f

requirements:
  host:
    - python
  build:
    - python
    - setuptools
    - wheel
    - jupyter-packaging
  run:
    - python
    - jupyterlab>=3.0.0

about:
  home: https://github.com/adhadse/theme-material-darcula
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "A Jupyterlab theme inspired by JetBrains IDE's Darcula scheme and Material Design."

extra:
  recipe-maintainers:
    - adhadse
